version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/conf.d/:/etc/mysql/conf.d/
      - /etc/timezone:/etc/timezone:ro      # ubuntu os
      - /etc/localtime:/etc/localtime:ro    # cent, mac os
      - ./mysql/initdb.d/:/docker-entrypoint-initdb.d/