@startuml

autonumber
hide footbox
participant "Server Application" as sa
participant "User App 1\n'111@abc.com'" as ua1
participant "User App 2\n'222@abc.com'" as ua2
participant "User App 3\n'333@abc.com'" as ua3
participant "User App 4\n'444@abc.com'" as ua4

== 4 users login ==

-> sa : invoke a conference call
note over sa : Call State is <b>IDLE</b>
sa -> ua1 : <b>JOIN</b> \n \
    { \n \
    \t"command": "JOIN", \n \
    \t"contents": { \n \
    \t\t"uuid": "user 1's uuid", \n \
    \t\t"roomid": "room number", \n \
    \t\t"participants": ["222@abc.com", \n\t\t\t\t\t\t"333@abc.com", \n\t\t\t\t\t\t"444@abc.com"]} \n \
    }
sa -> ua2 : <b>JOIN</b> \n \
    { \n \
    \t"command": "JOIN", \n \
    \t"contents": { \n \
    \t\t"uuid": "user 2's uuid", \n \
    \t\t"roomid": "room number", \n \
    \t\t"participants": ["111@abc.com", \n\t\t\t\t\t\t"333@abc.com", \n\t\t\t\t\t\t"444@abc.com"]} \n \
    }
sa -> ua3 : <b>JOIN</b> \n \
    { \n \
    \t"command": "JOIN", \n \
    \t"contents": { \n \
    \t\t"uuid": "user 3's uuid", \n \
    \t\t"roomid": "room number", \n \
    \t\t"participants": ["111@abc.com", \n\t\t\t\t\t\t"222@abc.com", \n\t\t\t\t\t\t"444@abc.com"]} \n \
    }
sa -> ua4 : <b>JOIN</b> \n \
    { \n \
    \t"command": "JOIN", \n \
    \t"contents": { \n \
    \t\t"uuid": "user 4's uuid", \n \
    \t\t"roomid": "room number", \n \
    \t\t"participants": ["111@abc.com", \n\t\t\t\t\t\t"222@abc.com", \n\t\t\t\t\t\t"333@abc.com"]} \n \
    }
|||
note over ua1, ua4 : 'JOIN' and 'CANCEL' buttons are enabled or displayed

== JOIN ==

ua1 -> sa : <b>JOIN</b> \n \
    { \n \
    \t"command": "JOIN", \n \
    \t"response": <b>"PARTICIPATE"</b> or "NOT PARTICIPATE", \n \
    \t"contents": { \n \
    \t\t"uuid": "user 1's uuid", \n \
    \t\t"roomid": "room number", \n \
    }

note over sa : Call State is CONFERENCE_CALL

ua1 -> sa : send Video/Voice data

ua2 -> sa : <b>JOIN</b> \n \
    { \n \
    \t"command": "JOIN", \n \
    \t"response": <b>"PARTICIPATE"</b> or "NOT PARTICIPATE", \n \
    \t"contents": { \n \
    \t\t"uuid": "user 2's uuid", \n \
    \t\t"roomid": "room number", \n \
    }

ua2 -> sa : send Video/Voice data

ua3 -> sa : <b>JOIN</b> \n \
    { \n \
    \t"command": "JOIN", \n \
    \t"response": <b>"PARTICIPATE"</b> or "NOT PARTICIPATE", \n \
    \t"contents": { \n \
    \t\t"uuid": "user 3's uuid", \n \
    \t\t"roomid": "room number", \n \
    }

ua3 -> sa : send Video/Voice data

ua4 -> sa : <b>JOIN</b> \n \
    { \n \
    \t"command": "JOIN", \n \
    \t"response": <b>"PARTICIPATE"</b> or "NOT PARTICIPATE", \n \
    \t"contents": { \n \
    \t\t"uuid": "user 4's uuid", \n \
    \t\t"roomid": "room number", \n \
    }

ua4 -> sa : send Video/Voice data

== LEAVE ==

ua1 -> sa : <b>LEAVE</b> \n \
    { \n \
    \t"command": "LEAVE", \n \
    \t"contents": { \n \
    \t\t"uuid": "user 1's uuid", \n \
    \t\t"email": "user 1's email", \n \
    \t\t"roomid": "room number", \n \
    }

note over sa : Call State is still CONFERENCE_CALL

sa -> ua2 : <b>LEAVE</b> \n \
    { \n \
    \t"command": "LEAVE", \n \
    \t"contents": { \n \
    \t\t"email": "user 1's email", \n \
    \t\t"roomid": "room number", \n \
    }

sa -> ua3 : <b>LEAVE</b> \n \
    { \n \
    \t"command": "LEAVE", \n \
    \t"contents": { \n \
    \t\t"email": "user 1's email", \n \
    \t\t"roomid": "room number", \n \
    }

sa -> ua4 : <b>LEAVE</b> \n \
    { \n \
    \t"command": "LEAVE", \n \
    \t"contents": { \n \
    \t\t"email": "user 1's email", \n \
    \t\t"roomid": "room number", \n \
    }

ua2 -> sa : <b>LEAVE</b> \n \
    { \n \
    \t"command": "LEAVE", \n \
    \t"contents": { \n \
    \t\t"uuid": "user 2's uuid", \n \
    \t\t"email": "user 2's email", \n \
    \t\t"roomid": "room number", \n \
    }

sa -> ua3 : <b>LEAVE</b> \n \
    { \n \
    \t"command": "LEAVE", \n \
    \t"contents": { \n \
    \t\t"email": "user 2's email", \n \
    \t\t"roomid": "room number", \n \
    }

sa -> ua4 : <b>LEAVE</b> \n \
    { \n \
    \t"command": "LEAVE", \n \
    \t"contents": { \n \
    \t\t"email": "user 2's email", \n \
    \t\t"roomid": "room number", \n \
    }

ua3 -> sa : <b>LEAVE</b> \n \
    { \n \
    \t"command": "LEAVE", \n \
    \t"contents": { \n \
    \t\t"uuid": "user 3's uuid", \n \
    \t\t"email": "user 3's email", \n \
    \t\t"roomid": "room number", \n \
    }

sa -> ua4 : <b>LEAVE</b> \n \
    { \n \
    \t"command": "LEAVE", \n \
    \t"contents": { \n \
    \t\t"email": "user 3's email", \n \
    \t\t"roomid": "room number", \n \
    }

ua4 -> sa : <b>LEAVE</b> \n \
    { \n \
    \t"command": "LEAVE", \n \
    \t"contents": { \n \
    \t\t"uuid": "user 4's uuid", \n \
    \t\t"email": "user 4's email", \n \
    \t\t"roomid": "room number", \n \
    }

note over sa : Conference call is ended

@enduml